INSERT INTO JOB_OFFER VALUES(1, 'Senior BE Developer', CURRENT_TIMESTAMP);
INSERT INTO JOB_OFFER VALUES(2, 'Junior BE Developer', CURRENT_TIMESTAMP);
INSERT INTO JOB_OFFER VALUES(3, 'Senior QA Developer', CURRENT_TIMESTAMP);